apiVersion: v1
kind: Service
metadata:
  labels:
    app: ise-portal
    type: Service
  name: svc-lb-ise-portal
  namespace: cicd
spec:
  type: LoadBalancer
  selector:
    app: ise-portal
  externalTrafficPolicy: Cluster
  ports:
  - name: http-ise-portal
    port: 80
    protocol: TCP
    targetPort: 5001
